#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean ElectromagneticModels/electromagneticModels
wclean ElectromagneticModels/coupledElectromagneticModels
wclean ElectromagneticModels/electroBase

wclean feedbackLoopController/feedbackLoopController

wclean modules/incompressibleConductingFluid
wclean modules/magneticMaterial
wclean modules/conductingMaterial
wclean modules/conductingFluid
wclean modules/conductingSolid
wclean modules/incompressibleConductingVoF

wclean moduleHandlers/conductingRegionSolver
wclean moduleHandlers/conductingRegionSolvers

wclean utilities/initializeTemperature
wclean utilities/initializeMultiRegionTemperature
wclean utilities/initializeRegionSolvers

wclean solvers/foamRunEpot
wclean solvers/foamMultiRunEpot

# ----------------------------------------------------------------- end-of-file
