#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake buoyantFoamMHD
wmake pimpleFoamMHD
wmake simpleFoamMHD
wmake buoyantFoamEpotTransient
wmake pimpleFoamEpotTransient
wmake buoyantFoamEpot
wmake pimpleFoamEpot
wmake simpleFoamEpot
wmake generateSimpleEOFFiles
wmake generatePimpleEOFFiles
wmake initializeTemperature
wmake chtMultiRegionFoamEpot

# ----------------------------------------------------------------- end-of-file
