#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake buoyantFoamMHD
wmake pimpleFoamMHD
wmake simpleFoamMHD

# ----------------------------------------------------------------- end-of-file
