#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean ElectromagneticModels/electromagneticModels
wclean ElectromagneticModels/coupledElectromagneticModels
wclean ElectromagneticModels/electroBase

wclean feedbackLoopController/feedbackLoopController

wclean modules/incompressibleConductingFluid
wclean modules/conductingMaterial
wclean modules/conductingFluid
wclean modules/conductingSolid

wclean moduleHandlers/conductingRegionSolver
wclean moduleHandlers/conductingRegionSolvers

wclean utilities/initializeTemperature
wclean utilities/initializeMultiRegionTemperature
wclean utilities/checkRegionCellZones
wclean utilities/findWireProperties

wclean solvers/foamRunEpot
wclean solvers/foamMultiRunEpot

# ----------------------------------------------------------------- end-of-file
