#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake buoyantFoamMHD
wmake pimpleFoamMHD
wmake simpleFoamMHD
wmake buoyantFoamEpot
wmake pimpleFoamEpot
wmake simpleFoamEpot

# ----------------------------------------------------------------- end-of-file
